import fs from "node:fs"
import path from "node:path"
import generate from "@babel/generator"
import * as t from "@babel/types"
import { glob } from "glob"

console.log("🚀 Generating index...")

const SOURCE_DIR = path.resolve(__dirname, "../src")
const INDEX_PATH = path.join(SOURCE_DIR, "index.ts")

async function generateIndex() {
	// Находим все TS-файлы кроме index.ts и файлов в исключенных директориях
	const files = await glob("**/*.ts", {
		cwd: SOURCE_DIR,
		ignore: ["index.ts", "**/*.d.ts", "**/__tests__/**", "**/__mocks__/**", "**/internal/**", "**/private/**"],
	})

	// Создаем массив экспортов и сортируем их
	const exports = files
		.map((file) => {
			const imp = file.replaceAll("\\", "/").replace(/\.ts$/, "")
			return `@/${imp}`
		})
		.sort()

	// Создаем AST дерево
	const exportNodes = exports.map((exp) => t.exportAllDeclaration(t.stringLiteral(exp)))

	// Создаем программу с экспортами
	const program = t.program(exportNodes)

	// Генерируем код из AST
	const { code } = generate(program)

	// Формируем окончательное содержимое файла
	const content = `// AUTO-GENERATED FILE. DO NOT EDIT.
// This file is automatically created by scripts/generate:index.ts.
// Use 'bun run generate:index' to regenerate.
/** biome-ignore-all assist/source/organizeImports: <AUTO-GENERATED> */

${code}
`

	// Записываем в файл
	fs.writeFileSync(INDEX_PATH, content, "utf-8")
	console.log(`✅ Generated ${INDEX_PATH} with ${exports.length} exports`)
}

generateIndex().catch(console.error)
