"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isKeywordNoConst = exports.isKeyword = exports.isRM = exports.valuesRM = exports.isBM = exports.valuesBM = exports.isChannel = exports.valuesChannel = exports.isConst = exports.valuesConst = exports.isFunction = exports.valuesFunction = exports.isDeviceParameter = exports.valuesDeviceParameter = exports.isSlotParameter = exports.valuesSlotParameter = void 0;
exports.valuesSlotParameter = ['ChargeRatio', 'Class', 'Damage', 'Efficiency', 'Growth', 'Health', 'Mature', 'MaxQuantity', 'OccupantHash', 'Occupied', 'Quantity', 'Seeding', 'SortingClass', 'x'];
const isSlotParameter = (val) => exports.valuesSlotParameter.includes(val);
exports.isSlotParameter = isSlotParameter;
exports.valuesDeviceParameter = ['Activate', 'AirRelease', 'Bpm', 'Charge', 'ClearMemory', 'CollectableGoods', 'Color', 'Combustion', 'CombustionInput', 'CombustionLimiter', 'CombustionOutput', 'CombustionOutput2', 'CompletionRatio', 'ElevatorLevel', 'ElevatorSpeed', 'Error', 'ExportCount', 'Filtration', 'Flush', 'ForceWrite', 'Fuel', 'HASH("name")', 'Harvest', 'Horizontal', 'Idle', 'ImportCount', 'InterrogationProgress', 'LineNumber', 'Lock', 'Maximum', 'MineablesInQueue', 'MineablesInVicinity', 'Minimum', 'MinimumWattsToContact', 'Mode', 'NextWeatherEventTime', 'On', 'Open', 'Output', 'Plant', 'PositionX', 'PositionY', 'PositionZ', 'Power', 'PowerActual', 'PowerGeneration', 'PowerPotential', 'PowerRequired', 'PrefabHash', 'Pressure', 'PressureAir', 'PressureExternal', 'PressureInput', 'PressureInternal', 'PressureOutput', 'PressureOutput2', 'PressureSetting', 'PressureWaste', 'Ratio', 'RatioCarbonDioxide', 'RatioCarbonDioxideInput', 'RatioCarbonDioxideOutput', 'RatioCarbonDioxideOutput2', 'RatioLiquidCarbonDioxide', 'RatioLiquidNitrogen', 'RatioLiquidNitrousOxide', 'RatioLiquidOxygen', 'RatioLiquidPollutant', 'RatioLiquidVolatiles', 'RatioNitrogen', 'RatioNitrogenInput', 'RatioNitrogenOutput', 'RatioNitrogenOutput2', 'RatioNitrousOxide', 'RatioNitrousOxideInput', 'RatioNitrousOxideOutput', 'RatioNitrousOxideOutput2', 'RatioOxygen', 'RatioOxygenInput', 'RatioOxygenOutput', 'RatioOxygenOutput2', 'RatioPollutant', 'RatioPollutantInput', 'RatioPollutantOutput', 'RatioPollutantOutput2', 'RatioSteam', 'RatioVolatiles', 'RatioVolatilesInput', 'RatioVolatilesOutput', 'RatioVolatilesOutput2', 'RatioWater', 'RatioWaterInput', 'RatioWaterOutput', 'RatioWaterOutput2', 'Reagents', 'RecipeHash', 'RequestHash', 'RequiredPower', 'ReturnFuelCost', 'Rpm', 'Setting', 'SettingOutput', 'SignalID', 'SignalStrength', 'SizeX', 'SizeZ', 'SolarAngle', 'SolarIrradiance', 'SoundAlert', 'Stress', 'TargetPadIndex', 'TargetX', 'TargetY', 'TargetZ', 'Temperature', 'TemperatureExternal', 'TemperatureInput', 'TemperatureOutput', 'TemperatureOutput2', 'TemperatureSetting', 'Throttle', 'Time', 'TotalMoles', 'TotalMolesInput', 'TotalMolesOutput', 'TotalMolesOutput2', 'VelocityMagnitude', 'VelocityRelativeX', 'VelocityRelativeY', 'VelocityRelativeZ', 'Vertical', 'Volume', 'VolumeOfLiquid', 'WattsReachingContact'];
const isDeviceParameter = (val) => exports.valuesDeviceParameter.includes(val);
exports.isDeviceParameter = isDeviceParameter;
exports.valuesFunction = ['abs', 'acos', 'add', 'alias', 'and', 'asin', 'atan', 'atan2', 'bap', 'bapal', 'bapz', 'bapzal', 'bdns', 'bdnsal', 'bdse', 'bdseal', 'beq', 'beqal', 'beqz', 'beqzal', 'bge', 'bgeal', 'bgez', 'bgezal', 'bgt', 'bgtal', 'bgtz', 'bgtzal', 'ble', 'bleal', 'blez', 'blezal', 'blt', 'bltal', 'bltz', 'bltzal', 'bna', 'bnaal', 'bnan', 'bnaz', 'bnazal', 'bne', 'bneal', 'bnez', 'bnezal', 'brap', 'brapz', 'brdns', 'brdse', 'breq', 'breqz', 'brge', 'brgez', 'brgt', 'brgtz', 'brle', 'brlez', 'brlt', 'brltz', 'brna', 'brnan', 'brnaz', 'brne', 'brnez', 'ceil', 'cos', 'debug', 'define', 'div', 'exp', 'floor', 'hcf', 'j', 'jal', 'jr', 'l', 'lb', 'lbn', 'lbns', 'lbs', 'log', 'lr', 'ls', 'max', 'min', 'mod', 'move', 'mul', 'nor', 'or', 'peek', 'pop', 'push', 'rand', 'return', 'round', 's', 'sap', 'sapz', 'sb', 'sbn', 'sbs', 'sdns', 'sdse', 'select', 'seq', 'seqz', 'sge', 'sgez', 'sgt', 'sgtz', 'sin', 'sla', 'sle', 'sleep', 'slez', 'sll', 'slt', 'sltz', 'sna', 'snan', 'snanz', 'snaz', 'sne', 'snez', 'sqrt', 'sra', 'srl', 'ss', 'stack', 'sub', 'tan', 'trunc', 'xor', 'yield'];
const isFunction = (val) => exports.valuesFunction.includes(val);
exports.isFunction = isFunction;
exports.valuesConst = ['Contents', 'Recipe', 'Required', 'deg2rad', 'nan', 'ninf', 'pi', 'pinf', 'rad2deg'];
const isConst = (val) => exports.valuesConst.includes(val);
exports.isConst = isConst;
exports.valuesChannel = ['Channel0', 'Channel1', 'Channel2', 'Channel3', 'Channel4', 'Channel5', 'Channel6', 'Channel7'];
const isChannel = (val) => exports.valuesChannel.includes(val);
exports.isChannel = isChannel;
exports.valuesBM = ['Average', 'Maximum', 'Minimum', 'Sum'];
const isBM = (val) => exports.valuesBM.includes(val);
exports.isBM = isBM;
exports.valuesRM = ['Contents', 'Required', 'Recipe'];
const isRM = (val) => exports.valuesRM.includes(val);
exports.isRM = isRM;
const isKeyword = (s) => (0, exports.isChannel)(s) || (0, exports.isSlotParameter)(s) || (0, exports.isDeviceParameter)(s) || (0, exports.isConst)(s);
exports.isKeyword = isKeyword;
const isKeywordNoConst = (s) => (0, exports.isChannel)(s) || (0, exports.isSlotParameter)(s) || (0, exports.isDeviceParameter)(s);
exports.isKeywordNoConst = isKeywordNoConst;
//# sourceMappingURL=icTypes.js.map