import { ic10Error } from "./ic10Error";
import { Memory } from "./Memory";
export declare const regexes: {
    rr1: RegExp;
    dr1: RegExp;
    r1: RegExp;
    d1: RegExp;
    strStart: RegExp;
    strEnd: RegExp;
};
export declare var Execution: {
    error(code: number, message: string, obj?: any): ic10Error;
    display: (e: {
        code: any;
        message: any;
        lvl: any;
        obj: any;
    }) => string | {
        code: any;
        message: any;
        lvl: any;
        obj: any;
    };
};
export declare class InterpreterIc10 {
    code: string;
    commands: {
        command: string | undefined;
        args: string[];
    }[];
    lines: string[];
    memory: Memory;
    position: number;
    interval: any;
    labels: {
        [key: string]: number;
    };
    constants: {};
    output: {
        debug: string;
        log: string;
        error: string;
    };
    settings: {
        debug: boolean;
        debugCallback: Function;
        logCallback: Function;
        executionCallback: Function;
        tickTime: number;
    };
    ignoreLine: Array<number>;
    constructor(code?: string, settings?: {});
    setSettings(settings?: object): InterpreterIc10;
    init(text: string): InterpreterIc10;
    stop(): InterpreterIc10;
    run(): Promise<unknown>;
    prepareLine(line?: number, isDebugger?: boolean): string | true;
    __issetLabel(x: string): boolean;
    define(alias: string, value: number | string): void;
    alias(alias: string | number, target: string | number): void;
    l(register: string, device: string, property: string): void;
    __l(register: string, device: string, property: string): void;
    ls(register: string, device: string, slot: string, property: string): void;
    s(device: string, property: string, value: string): void;
    __s(device: string, property: string, value: string): void;
    __op<Args extends number[]>(op: (...args: Args) => number, register: string, ...args: {
        [K in keyof Args]: string;
    }): void;
    move(register: string, value: string): void;
    __move(register: string, value: string): void;
    add(register: string, a: string, b: string): void;
    sub(register: string, a: string, b: string): void;
    mul(register: string, a: string, b: string): void;
    div(register: string, a: string, b: string): void;
    mod(register: string, a: string, b: string): void;
    sqrt(register: string, v: string): void;
    round(register: string, v: string): void;
    trunc(register: string, v: string): void;
    ceil(register: string, v: string): void;
    floor(register: string, v: string): void;
    max(register: string, a: string, b: string): void;
    minx(register: string, a: string, b: string): void;
    abs(register: string, v: string): void;
    log(register: string, v: string): void;
    exp(register: string, v: string): void;
    rand(register: string, v: string): void;
    sin(register: string, v: string): void;
    cos(register: string, v: string): void;
    tan(register: string, v: string): void;
    asin(register: string, v: string): void;
    acos(register: string, v: string): void;
    atan(register: string, v: string): void;
    atan2(register: string, a: string, b: string): void;
    yield(): void;
    sleep(s: number): void;
    select(register: string, a: string, b: string, c: string): void;
    hcf(): void;
    __jump(line: number): void;
    __call(line: number): void;
    __getJumpTarget(target: string): number;
    j(target: string): void;
    jr(offset: string): void;
    jal(target: string): void;
    __eq(a: number, b?: number): boolean;
    __ge(a: number, b?: number): boolean;
    __gt(a: number, b?: number): boolean;
    __le(a: number, b?: number): boolean;
    __lt(a: number, b?: number): boolean;
    __ne(a: number, b?: number): boolean;
    __ap(x: number, y: number, c?: number): boolean;
    __na(x: number, y: number, c?: number): boolean;
    __dse(d: string): boolean;
    __dns(d: string): boolean;
    __sOp<Args extends number[]>(op: (...args: Args) => boolean, register: string, ...args: {
        [K in keyof Args]: string;
    }): void;
    seq(register: string, a: string, b: string): void;
    seqz(register: string, a: string): void;
    sge(register: string, a: string, b: string): void;
    sgez(register: string, a: string): void;
    sgt(register: string, a: string, b: string): void;
    sgtz(register: string, a: string): void;
    sle(register: string, a: string, b: string): void;
    slez(register: string, a: string): void;
    slt(register: string, a: string, b: string): void;
    sltz(register: string, a: string): void;
    sne(register: string, a: string, b: string): void;
    snez(register: string, a: string): void;
    sap(register: string, x: string, y: string, c: string): void;
    sapz(register: string, x: string, y: string): void;
    sna(register: string, x: string, y: string, c: string): void;
    snaz(register: string, x: string, y: string): void;
    sdse(register: string, d: string): void;
    sdns(register: string, d: string): void;
    __bOp<Args extends number[]>(op: (...args: Args) => boolean | undefined, line: string, ...args: {
        [K in keyof Args]: string;
    }): void;
    __bROp<Args extends number[]>(op: (...args: Args) => boolean | undefined, offset: string, ...args: {
        [K in keyof Args]: string;
    }): void;
    beq(a: string, b: string, line: string): void;
    beqz(a: string, line: string): void;
    bge(a: string, b: string, line: string): void;
    bgez(a: string, line: string): void;
    bgt(a: string, b: string, line: string): void;
    bgtz(a: string, line: string): void;
    ble(a: string, b: string, line: string): void;
    blez(a: string, line: string): void;
    blt(a: string, b: string, line: string): void;
    bltz(a: string, line: string): void;
    bne(a: string, b: string, line: string): void;
    bnez(a: string, line: string): void;
    bap(x: string, y: string, c: string, line: string): void;
    bapz(x: string, y: string, line: string): void;
    bna(x: string, y: string, c: string, line: string): void;
    bnaz(x: string, y: string, line: string): void;
    bdse(d: string, line: string): void;
    bdns(d: string, line: string): void;
    breq(a: string, b: string, offset: string): void;
    breqz(a: string, offset: string): void;
    brge(a: string, b: string, offset: string): void;
    brgez(a: string, offset: string): void;
    brgt(a: string, b: string, offset: string): void;
    brgtz(a: string, offset: string): void;
    brle(a: string, b: string, offset: string): void;
    brlez(a: string, offset: string): void;
    brlt(a: string, b: string, offset: string): void;
    brltz(a: string, offset: string): void;
    brne(a: string, b: string, offset: string): void;
    brnez(a: string, offset: string): void;
    brap(x: string, y: string, c: string, offset: string): void;
    brapz(x: string, y: string, offset: string): void;
    brna(x: string, y: string, c: string, offset: string): void;
    brnaz(x: string, y: string, offset: string): void;
    brdse(d: string, offset: string): void;
    brdns(d: string, offset: string): void;
    beqal(op1: any, op2: any, op3: any, op4: any): void;
    beqzal(op1: any, op2: any, op3: any, op4: any): void;
    bgeal(op1: any, op2: any, op3: any, op4: any): void;
    bgezal(op1: any, op2: any, op3: any, op4: any): void;
    bgtal(op1: any, op2: any, op3: any, op4: any): void;
    bgtzal(op1: any, op2: any, op3: any, op4: any): void;
    bleal(op1: any, op2: any, op3: any, op4: any): void;
    blezal(op1: any, op2: any, op3: any, op4: any): void;
    bltal(op1: any, op2: any, op3: any, op4: any): void;
    bltzal(op1: any, op2: any, op3: any, op4: any): void;
    bneal(op1: any, op2: any, op3: any, op4: any): void;
    bnezal(op1: any, op2: any, op3: any, op4: any): void;
    bapal(op1: any, op2: any, op3: any, op4: any): void;
    bapzal(op1: any, op2: any, op3: any, op4: any): void;
    bnaal(op1: any, op2: any, op3: any, op4: any): void;
    bnazal(op1: any, op2: any, op3: any, op4: any): void;
    bdseal(op1: any, op2: any, op3: any, op4: any): void;
    bdnsal(op1: any, op2: any, op3: any, op4: any): void;
    push(op1: any, op2: any, op3: any, op4: any): void;
    pop(op1: any, op2: any, op3: any, op4: any): void;
    peek(op1: any, op2: any, op3: any, op4: any): void;
    lb(op1: any, op2: any, op3: any, op4: any): void;
    lr(op1: any, op2: any, op3: any, op4: any): void;
    sb(op1: any, op2: any, op3: any, op4: any): void;
    lbn(targetRegister: any, deviceHash: any, nameHash: any, property: any, batchMode: any): void;
    sbn(): void;
    lbs(): void;
    lbns(): void;
    ss(): void;
    sbs(): void;
    snan(): void;
    snanz(): void;
    bnan(): void;
    brnan(): void;
    and(register: string, a: string, b: string): void;
    or(op1: any, op2: any, op3: any, op4: any): void;
    xor(op1: any, op2: any, op3: any, op4: any): void;
    nor(op1: any, op2: any, op3: any, op4: any): void;
    _debug(op1: any, op2: any, op3: any, op4: any): void;
    _log(op1: any, op2: any, op3: any, op4: any): void;
    _d0(op1: any): void;
    _d1(op1: any): void;
    _d2(op1: any): void;
    _d3(op1: any): void;
    _d4(op1: any): void;
    _d5(op1: any): void;
    __d(device: string, args: any): void;
    __debug(p: string, iArguments: string[]): void;
}
export default InterpreterIc10;
