// Auto-generated file - DO NOT EDIT MANUALLY

import {
	BapalInstruction,
	BapInstruction,
	BapzalInstruction,
	BapzInstruction,
	BdnsalInstruction,
	BdnsInstruction,
	BdsealInstruction,
	BdseInstruction,
	BeqalInstruction,
	BeqInstruction,
	BeqzalInstruction,
	BeqzInstruction,
	BgealInstruction,
	BgeInstruction,
	BgezalInstruction,
	BgezInstruction,
	BgtalInstruction,
	BgtInstruction,
	BgtzalInstruction,
	BgtzInstruction,
	BlealInstruction,
	BleInstruction,
	BlezalInstruction,
	BlezInstruction,
	BltalInstruction,
	BltInstruction,
	BltzalInstruction,
	BltzInstruction,
	BnaalInstruction,
	BnaInstruction,
	BnanInstruction,
	BnazalInstruction,
	BnazInstruction,
	BnealInstruction,
	BneInstruction,
	BnezalInstruction,
	BnezInstruction,
	BrapInstruction,
	BrapzInstruction,
	BrdnsInstruction,
	BrdseInstruction,
	BreqInstruction,
	BreqzInstruction,
	BrgeInstruction,
	BrgezInstruction,
	BrgtInstruction,
	BrgtzInstruction,
	BrleInstruction,
	BrlezInstruction,
	BrltInstruction,
	BrltzInstruction,
	BrnaInstruction,
	BrnanInstruction,
	BrnazInstruction,
	BrneInstruction,
	BrnezInstruction,
	SapInstruction,
	SapzInstruction,
	SdnsInstruction,
	SdseInstruction,
	SelectInstruction,
	SeqInstruction,
	SeqzInstruction,
	SgeInstruction,
	SgezInstruction,
	SgtInstruction,
	SgtzInstruction,
	SleInstruction,
	SlezInstruction,
	SltInstruction,
	SltzInstruction,
	SnaInstruction,
	SnanInstruction,
	SnanzInstruction,
	SnazInstruction,
	SneInstruction,
	SnezInstruction,
} from "@/Ic10/Instruction/Condition";
import {
	BdnvlInstruction,
	BdnvsInstruction,
	ClrdInstruction,
	ClrInstruction,
	GetdInstruction,
	GetInstruction,
	LbInstruction,
	LInstruction,
	PutdInstruction,
	PutInstruction,
	SInstruction,
} from "@/Ic10/Instruction/Device";
import {
	JalInstruction,
	JeInstruction,
	JgeInstruction,
	JgtInstruction,
	JInstruction,
	JleInstruction,
	JltInstruction,
	JneInstruction,
	jrInstruction,
} from "@/Ic10/Instruction/Jump";
import {
	AbsInstruction,
	AcosInstruction,
	AddInstruction,
	AndInstruction,
	AsinInstruction,
	Atan2Instruction,
	AtanInstruction,
	CeilInstruction,
	CosInstruction,
	DivInstruction,
	ExpInstruction,
	ExtInstruction,
	FloorInstruction,
	InsInstruction,
	LerpInstruction,
	LogInstruction,
	MaxInstruction,
	MinInstruction,
	ModInstruction,
	MulInstruction,
	NorInstruction,
	NotInstruction,
	OrInstruction,
	PowInstruction,
	RandInstruction,
	RoundInstruction,
	SinInstruction,
	SlaInstruction,
	SllInstruction,
	SqrtInstruction,
	SraInstruction,
	SrlInstruction,
	SubInstruction,
	TanInstruction,
	TruncInstruction,
	XorInstruction,
} from "@/Ic10/Instruction/Math";
import { AliasInstruction } from "@/Ic10/Instruction/Misc/AliasInstruction";
import { DefineInstruction } from "@/Ic10/Instruction/Misc/DefineInstruction";
import { MoveInstruction } from "@/Ic10/Instruction/Misc/MoveInstruction";
import { HcfInstruction, SleepInstruction, YieldInstruction } from "@/Ic10/Instruction/Misc/OtherInstruction";
import {
	PeekInstruction,
	PokeInstruction,
	PopInstruction,
	PushInstruction,
} from "@/Ic10/Instruction/Misc/StackInstruction";

export type InstructionName = keyof typeof instructions;

export function isInstructionName(name: string): name is InstructionName {
	return name in instructions;
}

export const instructions = {
	abs: AbsInstruction,
	acos: AcosInstruction,
	add: AddInstruction,
	alias: AliasInstruction,
	and: AndInstruction,
	asin: AsinInstruction,
	atan: AtanInstruction,
	atan2: Atan2Instruction,
	bap: BapInstruction,
	bapal: BapalInstruction,
	bapz: BapzInstruction,
	bapzal: BapzalInstruction,
	bdns: BdnsInstruction,
	bdnsal: BdnsalInstruction,
	bdnvl: BdnvlInstruction,
	bdnvs: BdnvsInstruction,
	bdse: BdseInstruction,
	bdseal: BdsealInstruction,
	beq: BeqInstruction,
	beqal: BeqalInstruction,
	beqz: BeqzInstruction,
	beqzal: BeqzalInstruction,
	bge: BgeInstruction,
	bgeal: BgealInstruction,
	bgez: BgezInstruction,
	bgezal: BgezalInstruction,
	bgt: BgtInstruction,
	bgtal: BgtalInstruction,
	bgtz: BgtzInstruction,
	bgtzal: BgtzalInstruction,
	ble: BleInstruction,
	bleal: BlealInstruction,
	blez: BlezInstruction,
	blezal: BlezalInstruction,
	blt: BltInstruction,
	bltal: BltalInstruction,
	bltz: BltzInstruction,
	bltzal: BltzalInstruction,
	bna: BnaInstruction,
	bnaal: BnaalInstruction,
	bnan: BnanInstruction,
	bnaz: BnazInstruction,
	bnazal: BnazalInstruction,
	bne: BneInstruction,
	bneal: BnealInstruction,
	bnez: BnezInstruction,
	bnezal: BnezalInstruction,
	brap: BrapInstruction,
	brapz: BrapzInstruction,
	brdns: BrdnsInstruction,
	brdse: BrdseInstruction,
	breq: BreqInstruction,
	breqz: BreqzInstruction,
	brge: BrgeInstruction,
	brgez: BrgezInstruction,
	brgt: BrgtInstruction,
	brgtz: BrgtzInstruction,
	brle: BrleInstruction,
	brlez: BrlezInstruction,
	brlt: BrltInstruction,
	brltz: BrltzInstruction,
	brna: BrnaInstruction,
	brnan: BrnanInstruction,
	brnaz: BrnazInstruction,
	brne: BrneInstruction,
	brnez: BrnezInstruction,
	ceil: CeilInstruction,
	clr: ClrInstruction,
	clrd: ClrdInstruction,
	cos: CosInstruction,
	define: DefineInstruction,
	div: DivInstruction,
	exp: ExpInstruction,
	ext: ExtInstruction,
	floor: FloorInstruction,
	get: GetInstruction,
	getd: GetdInstruction,
	hcf: HcfInstruction,
	ins: InsInstruction,
	j: JInstruction,
	jal: JalInstruction,
	je: JeInstruction,
	jge: JgeInstruction,
	jgt: JgtInstruction,
	jle: JleInstruction,
	jlt: JltInstruction,
	jne: JneInstruction,
	jr: jrInstruction,
	l: LInstruction,
	lb: LbInstruction,
	lerp: LerpInstruction,
	log: LogInstruction,
	max: MaxInstruction,
	min: MinInstruction,
	mod: ModInstruction,
	move: MoveInstruction,
	mul: MulInstruction,
	nor: NorInstruction,
	not: NotInstruction,
	or: OrInstruction,
	peek: PeekInstruction,
	poke: PokeInstruction,
	pop: PopInstruction,
	pow: PowInstruction,
	push: PushInstruction,
	put: PutInstruction,
	putd: PutdInstruction,
	rand: RandInstruction,
	round: RoundInstruction,
	s: SInstruction,
	sap: SapInstruction,
	sapz: SapzInstruction,
	sdns: SdnsInstruction,
	sdse: SdseInstruction,
	select: SelectInstruction,
	seq: SeqInstruction,
	seqz: SeqzInstruction,
	sge: SgeInstruction,
	sgez: SgezInstruction,
	sgt: SgtInstruction,
	sgtz: SgtzInstruction,
	sin: SinInstruction,
	sla: SlaInstruction,
	sle: SleInstruction,
	sleep: SleepInstruction,
	slez: SlezInstruction,
	sll: SllInstruction,
	slt: SltInstruction,
	sltz: SltzInstruction,
	sna: SnaInstruction,
	snan: SnanInstruction,
	snanz: SnanzInstruction,
	snaz: SnazInstruction,
	sne: SneInstruction,
	snez: SnezInstruction,
	sqrt: SqrtInstruction,
	sra: SraInstruction,
	srl: SrlInstruction,
	sub: SubInstruction,
	tan: TanInstruction,
	trunc: TruncInstruction,
	xor: XorInstruction,
	yield: YieldInstruction,
} as const;
