# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "v4", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Building
        run: bunx tsc
      - name: Make folder
        run: mkdir build
      - name: Pack
        id: build
        run:  echo 'OUTPUT="$(npm pack)"' >> "$GITHUB_OUTPUT"
      - name: Rename
        run: mv "${{ steps.build.outputs.OUTPUT }}" "${{ steps.build.outputs.OUTPUT }}-${{ github.run_number }}-${{ steps.vars.outputs.sha_short }}"
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build.outputs.OUTPUT }}-${{ github.run_number }}-${{ steps.vars.outputs.sha_short }}
          retention-days: 60

